# Generated by Django 4.1 on 2023-12-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0004_route_planning_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="distance_km",
            field=models.FloatField(null=True),
        ),
    ]
