# Generated by Django 4.1 on 2023-12-17 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0006_location_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="location_end",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route_end",
                to="planning.location",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="location_start",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route_start",
                to="planning.location",
            ),
        ),
    ]
