# Generated by Django 4.1 on 2023-12-18 07:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0007_route_location_end_route_location_start"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationSearchResultData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("search_text", models.CharField(max_length=300, null=True)),
                ("display_name", models.CharField(max_length=300, null=True)),
                ("coordinates", models.CharField(max_length=300, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
