# Generated by Django 4.1 on 2024-01-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0008_locationsearchresultdata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LocationSearchResultData",
        ),
        migrations.AddField(
            model_name="location",
            name="country_code",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="postcode",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
