default_stages:
- commit
- manual
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.8
  hooks:
    # Run the Ruff linter.
    - id: ruff
      args: ["--fix"]
    # Run the Ruff formatter.
    - id: ruff-format