name: Backend tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Django environment
      run: |
        cd code
        python manage.py migrate

    - name: Run tests with coverage
      run: |
        cd code
        pytest --cov

    - name: Check coverage threshold
      run: |
        cd code
        pytest --cov --cov-report=xml
        coverage=$(grep -oP 'line-rate=".*?"' coverage.xml | grep -oP '".*?"' | tr -d '"' | awk '{print $1 * 100}')
        threshold=75  # Set your desired coverage threshold here
        if [ "$coverage" -lt "$threshold" ]; then
          echo "Coverage is below threshold $threshold% ($coverage%)."
          exit 1
        else
          echo "Coverage is acceptable ($coverage%)."
        fi