name: Python application CI

on:
  push:
    branches: [ main ]  # Execute on pushes to the main branch
  pull_request:
    branches: [ main ]  # Execute on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    - uses: actions/checkout@v2  # Checkout the repository content to the runner

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install project dependencies

    - name: Run tests with pytest
      run: |
        cd code
        pytest  # Run pytest command
