name: Backend tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Django environment
      run: |
        cd code
        python manage.py migrate

    - name: Run tests with coverage
      run: |
        cd code
        pytest --cov

    - name: Check coverage threshold
      run: |
        cd code
        pytest --cov --cov-report=xml
        coverage=$(grep -oP 'line-rate="[^"]+"' coverage.xml | cut -d'"' -f2)
        coverage_percentage=$(awk -v cov="$coverage" 'BEGIN { print int(cov * 100) }')
        threshold=80  # Set your desired coverage threshold here
        if [ "$coverage_percentage" -lt "$threshold" ]; then
          echo "Coverage is below threshold $threshold% ($coverage_percentage%)."
          exit 1
        else
          echo "Coverage is acceptable ($coverage_percentage% > $threshold%)."
        fi
